# 6. 에러와 예외처리
---
## 6.1 디버깅
- **버그란?**
    - 1945년 그레이스 호퍼가 최초로 버그를 발견
    - 역사상 최초의 버그는 소프트웨어적인 버그가 아니라, 실제 나방이 컴퓨터 회로에 들어가 합선을 일으켜 비정상적인 동작을 보인 것에서 유례

<br>

- **디버깅**
    - 잘못된 프로그램을 수정하는 것(de + bugging)
    - 에러 메시지가 발생
        - 해당 위치 찾아 에러 해결
    - 로직 에러 발생
        - 명시적인 에러 메시지가 없이 예상과 다른 결과가 나오는 경우
            - 정상적으로 동작한 코드 이후 작성된 코드를 확인
            - 전체 코드 확인
            - 휴식도 가져보고..
            - 동료한테도 물어보고..
            - ... 화이팅!
    - 제어가 되는 시점에 에러가 많음
        - 조건/반복, 함수 등
    
    - print 함수를 활용
    - 개발 환경에서 제공하는 기능 활용
        - breakpoint, 변수 조회
    - Python tutor 활용
    - 뇌컴파일, 눈디버깅

<br>

- **문법 에러**
    - SyntaxError 발생 시 파이썬 프로그램은 실행되지 않음
    - 파일이름, 줄번호, ^문자로 파이썬이 코드에서 에러 위치를 표현
    - 줄에서 에러가 발생한 경우 가장 앞의 위치를 가리키는 ^기호 표시
    - invalid syntax
        - 문법 오류
    - assign to literal
        - 잘못된 할당
    - EOL(End of Line)
        - 보통 괄호 안닫았을 때 
    - EOF(End of File)
        - 보통 괄호 안닫았을 때 2

- **예외(Exception)**
    - 실행 도중 예상치 못한 상황을 맞이하면, 프로그램 실행을 멈춤
        - 문장이나 표현식이 문법적으로 맞아도 발생
    - 실행 중에 감지되는 에러들을 예외라 부름
    - 예외는 타입이 여러 종류, 타입이 메시지로 출력됨
        - NameError, TypeError
    - 모든 내장 예외는 Exception Class를 상속 받음
    - 사용자 정의 예외 생성 및 관리 가능
    - **ZeroDivisionError**
        - 0으로 어떤 수를 나눌 때 발생
    - **NameError**
        - namespace에 이름이 없는 경우 발생
    - **TypeError**
        - 타입이 불일치한 경우 발생
        - 연산이 불가능한 type 끼리 연산을 시도할 때 발생
        - argument 누락 시 발생
        - argument 갯수 초과 시 발생
        - argument type이 불일치 할때 발생
    - **ValueError**
        - 타입은 올바르나 값이 적절하지 않거나 없을 때 발생
    - **IndexError**
        - 인덱스가 존재하지 않거나, 인덱스의 범위를 벗어나는 값을 입력했을 때 발생
    - **KeyError**
        - 해당 키가 존재하지 않는 경우 발생
    - **ModuleNotFoundError**
        - 모듈은 있으나 존재하지 않는 클래스나 함수를 가져오는 경우 발생
    - **KeyboardInterrupt**
        - 임의로 프로그램을 종료하였을 때 발생
    - **IndentationError**
        - Indentation이 올바르지 않을 경우 발생(들여쓰기)
    <br>

    - **파이썬 내장 예외**
        - [내장 예외 클래스 계층 구조](https://docs.python.org/ko/3/library/exceptions.html#exception-hierarchy)
        <br>


- **예외 처리**
    - try문, except절을 활용하여 예외 처리 가능
    - try문
        - 오류가 발생할 가능성이 있는 코드 실행하는 부분
        - 예외 발생하지 않으면 그대로 실행 종료
        <br>
    - except절
        - 예외가 발생하면 except절 실행
        - 예외 상황을 처리하는 코드를 입력하여 적절한 조치를 알려주기 위함
        <br>
    - 작성 예시
        ```python
        try:
            num = input('숫자를 입력하세요 :')
            print(int(num))
        
        except ValueError:
            print('올바른 숫자를 입력해 주세요')
        
        '''
        숫자를 입력하세요 : 3
        3
        '''

        '''
        숫자를 입력하세요 : 십
        올바른 숫자를 입력해 주세요
        '''

        ```
    <br>

    - 에러메시지 처리
        - as 키워드를 활용하여 원본 에러 메시지 사용 가능
            - 예외를 다른 이름에 대입 함
            ```python
             try:
                num = input('숫자를 입력하세요 :')
                print(int(num))

            except ValueError as err:
                print(f'{err}, 올바른 숫자를 입력해 주세요')
            
            '''
            숫자를 입력하세요 : 십
            invalid literal for int() with base 10: '십', 오류가 발생했습니다.
            '''
            ```
    <br>

    - 예외 처리 실습
        - 1을 사용자가 입력한 값으로 나누고 출력하는 코드
            - 발생 가능한 에러는?
                - TypeError(문자를 입력했을 경우)
                - ZeroDivisionError(0을 입력했을 경우)
        - 예상되는 에러는 모두 예외처리 필요!

    <br>
    
    - **예외처리 종합**
        - try: 코드 실행
        - except: try에서 예외 발생 시 실행
        - else: try문에서 예외가 발생하지 않으면 실행
        - finally: 예외 발생 여부와 관계없이 실행
    
    - 파일을 열고 읽는 코드 작성
        - 파일 열기 시도
            - 파일 없는 경우: '해당 파일을 찾을 수 없습니다' 출력(except)
            - 파일 있는 경우: 파일 내용 출력(else)
        - 해당 파일 읽기 작업 종료 메시지 출력(finally)
        ```python
        try:
            f = open('test.txt')
        except FileNotFoundError:
            print('해당 파일을 찾을 수 없습니다')
        else:
            print(f.read())
            f.close()
        finally:
            print('파일 읽기를 종료합니다')
        ```
        
